# Start with Ubuntu 14.04 (LTS), and build a Minion install up from there
FROM ubuntu:14.04
MAINTAINER April King <april@mozilla.com>
ENV MINION_DOCKERIZED true
ENV MINION_FRONTEND /opt/minion/minion-frontend
EXPOSE 8080
RUN apt-get update && apt-get install -y build-essential \
    curl \
    git \
    libcurl4-openssl-dev \
    python \
    python-dev \
    python-setuptools \
    stunnel

# Install minion-frontend
RUN git clone https://github.com/mozilla/minion-frontend.git ${MINION_FRONTEND}

# Move files into place
COPY frontend.json /tmp/frontend.json
COPY frontend.sh /tmp/frontend.sh
RUN chmod 755 /tmp/frontend.sh

# Setup the frontend environment
CMD /tmp/frontend.sh
